### PR TITLE
Init version

### PR DESCRIPTION
**Pull request by MalloZup**
# Description:

This PR port the exporter from my home repo to `suse` namespace.

It is a initial functional version of the exporter.

Many things were left over because for an initial version is ok to be concentrated to the essential part of it.

Also due to the rationale of this exporter, and prios we have I didn't invested much time on the Filesystem layout of the project , golang packages , etc this we can do later on.

I'm Adding Angela as CC reviewer just in case she spot something not saptune conform :)

### CODE REVIEW

**Comment by stefanotorresi** [comment]
hey @MalloZup great stuff, but could you please add at least one functional test like the ones we have in the other exporters? You can take the `sap_host_exporter` as the most up to date example. Otherwise I can't really see how the metrics are structured, without actually running the thing.

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
Hey here are a few other of things I'd like to see:
- We need to provide metrics docs, otherwise the semantics of the exporter are impossible to understand. Even just some examples with a few notes could suffice, you don't necessarily need to make them super-comprehensive from the start. We'll uniform the docs with the other exporters later, but we need at least some examples to start with and reason about.
- I think we should rename all the metric labels according to the naming convention we follow in all the other exporters, which is `snake_case` rather than `PascalCase`.
- Given our past experience, we shall try harder to avoid disappearing metrics, and rather list disabled things with an explicit 0, if possible.

**Comment by MalloZup** [comment]
Hi @stefanotorresi  thx for review. I will let this PR currently open a bit because i'm focusing on other things, currently.

I agree on the comments , I didn't had time to implement the missing things yet


Will address comments later on thx

**Comment by stefanotorresi** [comment]
no worries, there is no rush.

**Comment by MalloZup** [comment]
follow-up: https://github.com/SUSE/saptune_exporter/issues/4

**Comment by MalloZup** [comment]
@stefanotorresi  I adressed most of your comment with a follow-up issue for the metrics "disappering". For that particular case I think we could investigate if we can set them to 0, something I will look at.

I think for a first releases `0.1` this PR is ok now. (test + doc ) added.

**Review by angelabriel — COMMENTED** [review]
Great work, looks really good for me.
Many thanks for the work you spend to make saptune visible.

For the future we can add more saptune operations to the exporter and the new API Sören and I working on will help to make it a bit easier to adapt new stuff.
But be in mind, saptune is not providing dynamic data, the values are more of static nature. So it's not a typical metric.

**Comment by MalloZup** [comment]
thx @angelabriel

**Review by stefanotorresi — APPROVED** [review]
Perfect, @MalloZup! Top work!

**Pull request merged**
